### ISSUE TITLE
Reset MopFile Broken

### ISSUE THREAD

**Issue by Afrostie** [Afrostie/303COM-Project#2]
After fixing the seg faults, reset mopfile seems to be broken

**Comment by rucs-hack** [comment]
Ok, that's me then, I'll look at it tomorrow.

**Comment by Afrostie** [comment]
It might be, but I'm not 100% sure it is as it was only after I changed the way my skipping worked, it cycles through all 10 states, then gets stuck for a while until exiting with error constructing mopstate, might be that I need to alter the reset function slightly after the changes I made
